dist: xenial
language: python
python:
- '3.7'
- 3.7-dev
- 3.8-dev
- nightly
install:
- pip install -r requirements.txt
before_script: cd app
script:
- python app.py
before_install:
- openssl aes-256-cbc -K $encrypted_38e8b7ab3d42_key -iv $encrypted_38e8b7ab3d42_iv
  -in client-secret.json.enc -out client-secret.json -d
deploy:
    provider: gae
    # Skip cleanup so api_key.py and vendored dependencies are still there
    skip_cleanup: true
    keyfile: client-secret.json
    project: glass-gasket-249003
    default: true
    on:
        all_branches: true
