dist: xenial
language: python
sudo: required
python: "3.7"
install:
- pip install -r requirements.txt
before_script: cd app
script:
- python main.py

before_install:
- openssl aes-256-cbc -K $encrypted_38e8b7ab3d42_key -iv $encrypted_38e8b7ab3d42_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- mkdir -p lib

deploy:
  provider: gae
  skip_cleanup: true # Skip cleanup so api_key.py and vendored dependencies are still there
  keyfile: client-secret.json
  project: nasa-api-249022
  default: true  # default project app version

