dist: xenial
language: python
python:
- '3.7'
- 3.7-dev
- 3.8-dev
- nightly
install:
- pip install -r requirements.txt
before_script: cd app
script:
- python main.py

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: glass-gasket-249003
  default: true
  on:
    all_branches: true
